[buildPlans.IosevkaFoxV2]
family = "IosevkaFoxV2"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaFoxV2.variants]
  inherits = "ss08"

  [buildPlans.IosevkaFoxV2.ligations]
  inherits = "dlig"

[buildPlans.IosevkaFoxV2.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.IosevkaFoxV2.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaFoxV2.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaFoxV2.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaFoxV2.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaFoxV2.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaFoxV2.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaFoxV2.weights.Heavy]
shape = 900
menu = 900
css = 900
